version: 2.1
setup: true
orbs:
  config-splitting: circle-makotom-orbs/config-splitting@dev:0.0.7
workflows:
  setup:
    jobs:
      - config-splitting/run-modular-configs-selectively:
          base-revision: main
          module-list-file: .circleci/modules.txt
